# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfef2536fe491b30380ac22623550484"
name = "order-discount-itweek"
handle = "order-discount-itweek"
application_url = "https://australia-together-brazilian-burns.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extensibility-dev-store-jp-2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://australia-together-brazilian-burns.trycloudflare.com/auth/callback",
  "https://australia-together-brazilian-burns.trycloudflare.com/auth/shopify/callback",
  "https://australia-together-brazilian-burns.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
